name: Mala_MMOSkills
main: mala_mmoskill.main.MalaMMO_Skill
version: 1.18.1
api-version: 1.18
author: Malaia_Garnet
description: Adds some mmocore skills
depend: [Laylia_Core_API, LibsDisguises, MythicMobs, MMOCore]
softdepend: [Spartan, Quests, ItemsAdder]
commands:
   MM_ChangeClass:
      description: change player class. no level initialization.
      usage: /MM_ChangeClass <playername> <class_id>
      default: true
   MM_SkillReAlloc:
      description: re allocate player skills
      usage: /MM_SkillReAlloc
      default: true
   MM_StatReAlloc:
      description: re allocate player stats
      usage: /MM_StatReAlloc
      default: true
   MM_ReduceMode:
      description: reduce player skill particle
      usage: /MM_ReduceMode
      default: true
   mm_xmasEffect:
      description: reduce player skill particle
      usage: /mm_xmasEffect
      default: true
permissions: